sandboxNamespace: "###ZARF_VAR_JOB_RUNNER_NAMESPACE###"

# whether to have the Zarf Agent ignore the sandbox namespace
sandboxZarfIgnore: true

serviceAccountName: "gitlab-runner"

custom: []
  # - direction: Egress
  #   remoteGenerated: Anywhere
  #   description: "Egress from to external GitLab"
customSandbox: []
  # - direction: Egress
  #   remoteGenerated: Anywhere
  #   description: "Egress from to external GitLab"
