# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# which executor to use, either 'kubernetes' or 'instance'
executor: "kubernetes"

sandboxNamespace: "###ZARF_VAR_RUNNER_SANDBOX_NAMESPACE###"

# whether to have the Zarf Agent ignore the sandbox namespace
sandboxZarfIgnore: true

serviceAccountName: "gitlab-runner"

runnerAuthToken: "###ZARF_VAR_RUNNER_AUTH_TOKEN###"

enableSecurityCapabilities: false

custom: []
  # - direction: Egress
  #   remoteGenerated: Anywhere
  #   description: "Egress from to external GitLab"
customSandbox: []
  # - direction: Egress
  #   remoteGenerated: Anywhere
  #   description: "Egress from to external GitLab"
