# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# This allows the runner to install on UBI-based images (https://gitlab.com/gitlab-org/charts/gitlab-runner/-/blob/main/values.yaml?ref_type=heads#L20)
useTini: true

image:
  registry: "quay.io"
  image: "rfcurated/gitlab/gitlab-runner"
  # renovate: datasource=docker depName=quay.io/rfcurated/gitlab/gitlab-runner versioning=semver
  tag: 18.4.0-jammy-fips-rfcurated

runners:
  job:
    registry: "###ZARF_REGISTRY###"
    repository: rfcurated/rfubu
    # renovate: datasource=docker depName=quay.io/rfcurated/rfubu versioning=docker
    tag: 22.04-scratch-fips-rfcurated
  helper:
    registry: "###ZARF_REGISTRY###"
    repository: rfcurated/gitlab/gitlab-runner-helper
    # renovate: datasource=docker depName=quay.io/rfcurated/gitlab/gitlab-runner-helper versioning=semver
    tag: 18.4.0-jammy-fips-rfcurated
