# action.yml
name: "Setup Environment"
description: "UDS Environment Setup"

inputs:
  username:
    description: Registry1 user
    required: true
  password:
    description: Registry1 PW
    required: true
  download-init-package:
    description: "whether to download the zarf init package or not"
    default: "true"
  install-k3d:
    description: "whether to install k3d or not"
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Login to Registry1
      uses: docker/login-action@v3
      with:
        registry: registry1.dso.mil
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@main
      with:
        # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
        version: v0.32.1
        download-init-package: ${{ inputs.download-init-package }}

    - name: Install k3d
      if: ${{ inputs.install-k3d }}
      shell: bash
      run: curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.6.0 bash

    - name: Setup Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install UDS CLI
      shell: bash
      # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
      run: brew install defenseunicorns/tap/uds@0.6.1
