# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if eq .Values.executor "kubernetes" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.sandboxNamespace }}
  {{- if .Values.sandboxZarfIgnore }}
  labels:
    zarf.dev/agent: ignore
  {{- end }}
{{- end }}
