# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: v1
kind: Secret
metadata:
  name: gitlab-gitlab-runner-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  runner-registration-token: ""
  runner-token: {{ .Values.runnerAuthToken }}
