apiVersion: v1
kind: Secret
metadata:
  name: gitlab-gitlab-runner-secret
  namespace: {{ .Values.runners.job.namespace }}
type: Opaque
stringData:
  runner-registration-token: {{ (lookup "v1" "Secret" "gitlab" "gitlab-gitlab-runner-secret").data["runner-registration-token"] | b64dec }}
  runner-token: ""
