apiVersion: v1
kind: Secret
metadata:
  name: gitlab-gitlab-runner-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  runner-registration-token: ""
  runner-token: {{ index (lookup "v1" "Secret" "gitlab" "gitlab-gitlab-runner-secret").data "runner-token" | b64dec }}
