apiVersion: v1
kind: Secret
metadata:
  name: gitlab-gitlab-runner-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  runner-registration-token: ""
  runner-token: {{ .Values.runnerAuthToken }}
