apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.runners.job.namespace }}
  labels:
    istio-injection: enabled
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.runners.job.namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "pods/attach", "secrets", "services"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.runners.job.namespace }}
  namespace: {{ .Values.runners.job.namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: gitlab-runner
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: {{ .Values.runners.job.namespace }}