# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if eq .Values.executor "kubernetes" }}
apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: gitlab-runner-sandbox
  namespace: {{ .Values.kubernetesSandbox.namespace }}
spec:
  network:
    serviceMesh:
      mode: ambient
    allow:
      - direction: Ingress
        selector: 
          uds/network-access-gitlab: "true"
        remoteNamespace: gitlab-runner
        remoteSelector:
          app: gitlab-runner

      # Allow access to other UDS services (i.e. gitlab.<domain>, sonarqube.<domain>) from the runner
      - direction: Egress
        remoteNamespace: istio-{{ .Values.gateway }}-gateway
        remoteSelector:
          app: {{ .Values.gateway }}-ingressgateway
        selector: 
          uds/network-access-gitlab: "true"
        port: 443
        description: "UDS {{ .Values.gateway }} Gateway Services"

    {{- range .Values.kubernetesSandbox.additionalNetworkAllow }}
      - direction: {{ .direction }}
        selector:
          {{ .selector | toYaml | nindent 10 }}
        {{- if not .remoteGenerated }}
        remoteNamespace: {{ .remoteNamespace }}
        remoteSelector:
          {{ .remoteSelector | toYaml | nindent 10 }}
        port: {{ .port }}
        {{- else }}
        remoteGenerated: {{ .remoteGenerated }}
        {{- end }}
        description: {{ .description }}
    {{- end }}
{{- end }}
