# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if .Values.kubernetesSandbox.enableSecurityExceptions }}
apiVersion: uds.dev/v1alpha1
kind: Exemption
metadata:
  name: gitlab-runner-container-building
  namespace: uds-policy-exemptions
spec:
  exemptions:
    - description: Allow more capabilities for container build tools (Buildah) to be able to map user and group IDs
      policies:
        - RestrictCapabilities
        - DisallowPrivileged
      title: "gitlab-runner-container-building"
      matcher:
        namespace: gitlab-runner-sandbox
        name: "^runner-.*"
{{- end }}
