apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: gitlab-runner
  namespace: {{ .Release.Namespace }}
spec:
  monitor:
    - selector:
        app: gitlab-runner 
      targetPort: 9252
      portName: metrics
      description: Metrics

  network:
    allow:
      - direction: Egress
        selector:
          app: gitlab-runner
        remoteNamespace: gitlab
        remoteSelector:
          app: webservice
        port: 8181

      - direction: Egress
        podLabels:
          app: gitlab-runner
        remoteGenerated: KubeAPI

      - direction: Egress
        selector:
          app: gitlab-runner
        remoteNamespace: {{ .Values.sandboxNamespace }}
        remoteSelector:
          uds/network-access-gitlab: true
        
      # Custom rules for unanticipated scenarios
    {{- range .Values.custom }}
      - direction: {{ .direction }}
        selector:
          {{ .selector | toYaml | nindent 10 }}
        {{- if not .remoteGenerated }}
        remoteNamespace: {{ .remoteNamespace }}
        remoteSelector:
          {{ .remoteSelector | toYaml | nindent 10 }}
        port: {{ .port }}
        {{- else }}
        remoteGenerated: {{ .remoteGenerated }}
        {{- end }}
        description: {{ .description }}
    {{- end }}
