apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: gitlab-runner-sandbox
  namespace: {{ .Values.runnerNamespace }}
spec:
  network:
    allow:
      - direction: Egress
        remoteNamespace: gitlab
        remoteSelector:
          app: webservice
        port: 8181

      - direction: Ingress
        remoteGenerated: IntraNamespace

      - direction: Egress
        remoteGenerated: IntraNamespace

      - direction: Egress
        remoteNamespace: gitlab-runner
        remoteSelector:
          app: gitlab-runner

      - direction: Ingress
        remoteNamespace: gitlab-runner
        remoteSelector:
          app: gitlab-runner

      - direction: Egress
        remoteGenerated: KubeAPI

    {{- range .Values.customSandbox }}
      - direction: {{ .direction }}
        selector:
          {{ .selector | toYaml | nindent 10 }}
        {{- if not .remoteGenerated }}
        remoteNamespace: {{ .remoteNamespace }}
        remoteSelector:
          {{ .remoteSelector | toYaml | nindent 10 }}
        port: {{ .port }}
        {{- else }}
        remoteGenerated: {{ .remoteGenerated }}
        {{- end }}
        description: {{ .description }}
    {{- end }}
