# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: gitlab-runner
  namespace: {{ .Release.Namespace }}
spec:
  monitor:
    - selector:
        app: gitlab-runner 
      targetPort: 9252
      portName: http-metrics
      description: Metrics

  network:
    allow:
      # Allow access to other UDS services (i.e. gitlab.<domain>, sonarqube.<domain>) from the runner
      - direction: Egress
        remoteNamespace: istio-tenant-gateway
        remoteSelector:
          app: tenant-ingressgateway
        selector:
          app: gitlab-runner
        port: 443
        description: "UDS Tenant Gateway Services"

    {{- if eq .Values.executor "kubernetes" }}
      - direction: Egress
        podLabels:
          app: gitlab-runner
        remoteGenerated: KubeAPI

      - direction: Egress
        selector:
          app: gitlab-runner
        remoteNamespace: {{ .Values.kubernetesSandbox.namespace }}
        remoteSelector:
          uds/network-access-gitlab: "true"
    {{- end }}

    {{- if has .Values.executor (list "instance" "docker-autoscaler") }}
      - direction: Ingress
        remoteGenerated: IntraNamespace
      - direction: Egress
        podLabels:
          app: gitlab-runner
        remoteGenerated: Anywhere
    {{- end }}

      # Custom rules for unanticipated scenarios
    {{- range .Values.additionalNetworkAllow }}
      - direction: {{ .direction }}
        selector:
          {{ .selector | toYaml | nindent 10 }}
        {{- if not .remoteGenerated }}
        remoteNamespace: {{ .remoteNamespace }}
        remoteSelector:
          {{ .remoteSelector | toYaml | nindent 10 }}
        port: {{ .port }}
        {{- else }}
        remoteGenerated: {{ .remoteGenerated }}
        {{- end }}
        description: {{ .description }}
    {{- end }}
