apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: gitlab-runner
  namespace: {{ .Release.Namespace }}
spec:
  monitor:
    - selector:
        app: gitlab-runner 
      targetPort: 9252
      portName: metrics
      description: Metrics

  network:
    allow:
      # Allow access to other UDS services (i.e. gitlab.<domain>, sonarqube.<domain>) from the runner
      - direction: Egress
        remoteNamespace: istio-tenant-gateway
        remoteSelector:
          app: tenant-ingressgateway
        selector:
          app: gitlab-runner
        port: 443
        description: "UDS Tenant Gateway Services"

      - direction: Egress
        podLabels:
          app: gitlab-runner
        remoteGenerated: KubeAPI

      - direction: Egress
        selector:
          app: gitlab-runner
        remoteNamespace: {{ .Values.sandboxNamespace }}
        remoteSelector:
          uds/network-access-gitlab: "true"

      # Custom rules for unanticipated scenarios
    {{- range .Values.custom }}
      - direction: {{ .direction }}
        selector:
          {{ .selector | toYaml | nindent 10 }}
        {{- if not .remoteGenerated }}
        remoteNamespace: {{ .remoteNamespace }}
        remoteSelector:
          {{ .remoteSelector | toYaml | nindent 10 }}
        port: {{ .port }}
        {{- else }}
        remoteGenerated: {{ .remoteGenerated }}
        {{- end }}
        description: {{ .description }}
    {{- end }}
