includes:
  - dependencies: ./dependencies.yaml
  - test: ./test.yaml
  - create: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.5.1/tasks/create.yaml
  #- publish: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.5.1/tasks/publish.yaml
  - deploy: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.5.1/tasks/deploy.yaml
  - setup: https://raw.githubusercontent.com/defenseunicorns/uds-common/v0.5.1/tasks/setup.yaml

tasks:
  - name: package
    description: Build and publish the packages
    actions:
      - task: create:package
      - task: create:test-bundle
      - task: setup:k3d-test-cluster
      - task: dependencies:deploy
      - task: deploy:test-bundle
      - task: test:glr-health-check
      - task: test:glr-run-check
