# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

variables:
  - name: REGION
  - name: STATE_BUCKET_NAME
  - name: STATE_DYNAMODB_TABLE_NAME
  - name: STATE_KEY

tasks:
  - name: destroy-iac
    actions:
      - cmd: tofu destroy -auto-approve
        dir: .github/test-infra/asg-iac

  - name: apply-iac
    actions:
      - cmd: echo "${STATE_KEY}" | sed 's/\.tfstate/-buckets1.tfstate/g'
        setVariables:
          - name: BUCKETS_STATE_KEY
        dir: .github/test-infra/asg-iac
      - cmd: echo "${BUCKETS_STATE_KEY}"
      - cmd: |
          tofu init -force-copy \
          -backend-config="bucket=${STATE_BUCKET_NAME}" \
          -backend-config="key=${BUCKETS_STATE_KEY}" \
          -backend-config="region=${REGION}" \
          -backend-config="dynamodb_table=${STATE_DYNAMODB_TABLE_NAME}"
        dir: .github/test-infra/asg-iac
      - cmd: tofu apply -auto-approve
        dir: .github/test-infra/asg-iac

  - name: plan-iac
    actions:
      - cmd: echo "${STATE_KEY}" | sed 's/\.tfstate/-buckets1.tfstate/g'
        setVariables:
          - name: BUCKETS_STATE_KEY
        dir: .github/test-infra/asg-iac
      - cmd: echo "${BUCKETS_STATE_KEY}"
      - cmd: |
          tofu init -force-copy \
          -backend-config="bucket=${STATE_BUCKET_NAME}" \
          -backend-config="key=${BUCKETS_STATE_KEY}" \
          -backend-config="region=${REGION}" \
          -backend-config="dynamodb_table=${STATE_DYNAMODB_TABLE_NAME}"
        dir: .github/test-infra/asg-iac
      - cmd: tofu plan -out terraform.plan
        dir: .github/test-infra/asg-iac
