tasks:
  - name: k3d-test-cluster
    actions:
      - description: Setup k3d cluster with UDS Core
        cmd: uds deploy oci://defenseunicorns/uds/bundles/k3d-core-istio:0.8.0-amd64 --confirm --no-progress

  - name: gitlab-runner-secret
    actions:
      - description:
        cmd: kubectl create namespace gitlab-runner && kubectl apply -f src/dev-secrets/runner-secret.yaml