tasks:
  - name: k3d-test-cluster
    actions:
      - description: Setup k3d cluster with UDS Core
        cmd: uds deploy oci://defenseunicorns/uds/bundles/upstream/k3d-core-istio:0.9.1-${UDS_ARCH} --confirm --no-progress


  - name: gitlab-runner-namespace
    actions:
      - description: Create gitlab-runner namespace
        cmd: kubectl create namespace gitlab-runner

  - name: gitlab-runner-secret
    actions:
      - description: Retrieve Gitlab Package gitlab runner secret registration token
        cmd: kubectl get secret gitlab-gitlab-runner-secret -n gitlab -o=jsonpath={.data.runner-registration-token} | base64 -d
        setVariables:
          - name: RUNNER_REGISTRATION_TOKEN
      - description: Create gitlab-runner namespace and secret
        cmd:  kubectl create secret generic gitlab-gitlab-runner-secret --namespace=gitlab-runner --from-literal=runner-registration-token="${RUNNER_REGISTRATION_TOKEN}" --from-literal=runner-token="" --v=9 || true
