
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: gitlab-postgresql-exception
  namespace: gitlab
spec:
  mtls:
    mode: STRICT
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  portLevelMtls:
    "5432":
      mode: PERMISSIVE

