apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: gitlab-redis-exception
  namespace: gitlab
spec:
  mtls:
    mode: STRICT
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  portLevelMtls:
    "6379":
      mode: PERMISSIVE
    "9121":
      mode: PERMISSIVE

