name: Tag and Publish UDS Capability

on:
  push:
    branches:
      - ewyles/pre-release-testing

permissions:
  contents: read
  packages: write

jobs:
  publish-package:
    runs-on: ${{ matrix.architecture == 'arm64' && 'uds-ubuntu-big-boy-8-core' || 'ubuntu-latest' }}
    strategy:
      matrix:
        flavor: [upstream, registry1]
        architecture: [arm64]
        exclude:
          - flavor: registry1
            architecture: arm64
    name: Publish ${{ matrix.flavor }} ${{ matrix.architecture }}

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Environment setup
        uses: defenseunicorns/uds-common/.github/actions/setup@d50b4ebe3712fea4114289db0c36da61a5f60eb5 # v0.5.1
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Package
        run: UDS_ARCHITECTURE=${{ matrix.architecture }} uds run -f tasks/ewyles-temp.yaml package --set FLAVOR=${{ matrix.flavor }}

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/save-logs@d50b4ebe3712fea4114289db0c36da61a5f60eb5 # v0.5.1
        with:
          suffix: ${{ matrix.flavor }}-${{ github.run_id }}-${{ github.run_attempt }}
