# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Plan Tofu

on:
  pull_request:
    branches: [main]
    types: [milestoned, opened, synchronize]
    paths:
      - ".github/test-infra/asg-iac/*"
      - ".github/workflows/plan-tofu.yaml"
      - "tasks/iac.yaml"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: plan-tofu-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  nightly-testing:
    name: Plan Tofu for Fleeting GitLab Runners
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [upstream, registry1]
      fail-fast: false
    env:
      SHA: ${{ github.sha }}
      FLAVOR: ${{ matrix.flavor }}
      UDS_REGION: us-gov-west-1
      UDS_STATE_BUCKET_NAME: uds-ci-govcloud-us-gov-west-1-tfstate
      UDS_STATE_DYNAMODB_TABLE_NAME: uds-ci-govcloud-tfstate-lock
      TF_VAR_ami_id: ${{ secrets.AMI_ID }}
      TF_VAR_permissions_boundary_name: ${{ secrets.PERMISSIONS_BOUNDARY_NAME }}
    steps:
      - name: Set ENV
        run: |
          printf "%s\n" \
            "UDS_GITLAB_RUNNER_AUTOSCALING_GROUP=uds-package-gitlab-runner-ci-${FLAVOR}-${SHA:0:7}" \
            "UDS_STATE_KEY=tfstate/ci/install/${SHA:0:7}-gitlab-runner-${FLAVOR}-aws.tfstate" \
            "TF_VAR_runner_ip=$(curl -s https://api.ipify.org)" \
            "TF_VAR_region=${UDS_REGION}" \
            "TF_VAR_name=uds-package-gitlab-runner-ci-${FLAVOR}-${SHA:0:7}" \
            >> "$GITHUB_ENV"
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Install UDS CLI
        uses: defenseunicorns/setup-uds@b987a32bac3baeb67bfb08f5e1544e2f9076ee8a # v1.0.0
        with:
          # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
          version: 0.18.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: ${{ secrets.AWS_GOVCLOUD_ROLE_TO_ASSUME }}
          role-session-name: ${{ github.job || github.event.client_payload.pull_request.head.sha || github.sha }}
          aws-region: ${{ env.UDS_REGION }}
          role-duration-seconds: 21600

      - name: Setup Tofu
        uses: opentofu/setup-opentofu@12f4debbf681675350b6cd1f0ff8ecfbda62027b # v1.0.4
        with:
          tofu_version: 1.8.1
          tofu_wrapper: false

      - name: Plan IAC
        run: uds run -f tasks/iac.yaml plan-iac --no-progress
        timeout-minutes: 20
