name: Publish Zarf Package

on:
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [upstream, registry1]

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup
        with:
          username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          install-k3d: false
          download-init-package: false

      - name: Login to GHCR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish gitlab runner package
        run: uds run -f tasks/publish.yaml package --set FLAVOR=${{ matrix.flavor }}
