# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Scan

on:
  # This workflow is triggered on pull requests to the main branch.
  pull_request:
    paths:
      - zarf.yaml
      - releaser.yaml
      - .release-please-manifest.json

jobs:
  scan:
    permissions:
      contents: read # Allows reading the content of the repository.
      packages: read # Allows reading the content of the repository's packages.
      id-token: write # Allows authentication to Chainguard via OIDC.
      pull-requests: write # Allows writing the scan results comment to the pull request.
    uses: defenseunicorns/uds-common/.github/workflows/callable-scan.yaml@4f46bb2110abc2c994ad242b099822de71de1ecc # v1.20.5
    secrets: inherit # Inherits all secrets from the parent workflow.
