name: Test package

on:
  pull_request:
    # milestoned is added here as a workaround for release-please not triggering PR workflows (PRs should be added to a milestone to trigger the workflow).
    types: [milestoned, opened, reopened, synchronize]

# Abort prior jobs in the same workflow / PR
concurrency:
  group: test-${{ github.ref }}-${{ inputs.package }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: "uds-ubuntu-big-boy-16-core"
    name: Test
    strategy:
      matrix:
        flavor: [upstream, registry1]    

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Environment setup
        uses: ./.github/actions/setup
        with:
          username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}

      - name: Standup k3d Cluster and UDS Package Gitlab and Deploy UDS Gitlab Runner
        run: uds run default --set FLAVOR=${{ matrix.flavor }}

      - name: Run Health Check Tests for Gitlab and Gitlab Runner
        run: uds run test-package

      - name: Cleanup the k3d Cluster
        if: always()
        run: uds run cleanup-cluster

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/save-logs@fc12e3a773580020a1d63e254525eab0f8b99fc8
        with:
          suffix: '${{ matrix.flavor }}-${{ github.run_id }}-${{ github.run_attempt }}'
