name: Test package

on:

  # Branch Push Trigger
  push:

  # Manual trigger
  workflow_dispatch:

  # Triggered by pull-request-conditionals.yaml
  workflow_call:

# Abort prior jobs in the same workflow / PR
concurrency:
  group: test-${{ github.ref }}-${{ inputs.package }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: "ubuntu-latest"
    timeout-minutes: 20
    name: Test

    steps:
      - name: Checkout repository
        uses: actions/checkout@4

      - name: Environment setup
        uses: ./.github/actions/setup

      - name: Standup k3d Cluster and Gitlab Yolo and Deploy UDS Gitlab Runner
        run: uds run cluster-full

      - name: Run Health Check Tests for Gitlab and Gitlab Runner
        run: uds run test-package

      - name: Cleanup the k3d Cluster
        if: always()
        run: uds run cleanup-cluster

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
